name: "Setup Node.js and Dependencies"
description: "Setup Node.js environment, pnpm, cache, and install dependencies"

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
    - run: pnpm install --frozen-lockfile
      shell: bash
