name: CI

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        check: [eslint, typecheck, prettier]

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: pnpm lint:${{ matrix.check }}

  Test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: pnpm test
