name: CI

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  TypeCheck:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: pnpm type-check
